version: "3.8"
services:
  api-service:
    build: ./backend/
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
  client:
    container_name: react-app
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
